List<Map<String, dynamic>> kanjiData = [
  {
    'character': '山',
    'translation': 'Mountain',
    'sentence': '3 peaks group together to form a big mountain.',
    'Kun':'yama (やま)',
    'On':'san (サン)',
    'image':'kanji_mountain.gif',
  },
  {
    'character': '口',
    'translation': 'Mouth',
    'sentence': 'A man has his mouth wide open when he is shocked.',
    'Kun':'ku (ク), ko (コウ)',
    'On':'kuchi (くち)',
    'image':'kanji_mouth.gif',
  },
  {
    'character': '日',
    'translation': 'Sun',
    'sentence': 'A beautiful sunset appears over the  horizon of the sea.',
    'Kun':'ka (か), hi (ひ)',
    'On':'jitsu (ジツ), nichi (ニチ)',
    'image':'kanji_sun.gif',
  },
  {
    'character': '川',
    'translation': 'River',
    'sentence': 'A rocky river has 3 lines of stream flow.',
    'Kun':'kawa (かわ)',
    'On':'sen (セン)',
    'image':'kanji_river.gif',
  },
  {
    'character': '田',
    'translation': 'Rice Field',
    'sentence': '4 rice fields form a square pattern.',
    'Kun':'ta (た)',
    'On':'den (デン)',
    'image':'kanji_rice_field.gif',
  },
  {
    'character': '木',
    'translation': 'Tree',
    'sentence': 'A tree grows 3 branches and 3 roots.',
    'Kun':'ki (き), ko (こ)',
    'On':'boku (ボク), moku (モク)',
    'image':'kanji_tree.gif',
  },
  {
    'character': '水',
    'translation': 'Water',
    'sentence': 'A water droplet fills with many reflections.',
    'Kun':'mizu (みず)',
    'On':'sui (スイ)',
    'image':'kanji_water.gif',
  },
];