name: zeny
description: "Brush away your bad mood"
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  gap: ^3.0.1
  audioplayers: ^6.4.0
  awesome_notifications: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sound/
    - assets/animations/


flutter_launcher_icons:
  android: "ic_launcher"
  ios: "AppIcon"
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true